### PR TITLE
OPENG-334 make proxy consistent with /ripjar/passport-openidconnect/pull/3

### PR DESCRIPTION
**Pull request by jjhoughton**
make the way it does the proxy consistent with what Jordan did
in passport-openidconnect.

### CODE REVIEW

**Comment by SteveJM** [comment]
It would be useful to have an initial commit with thew forked code and then a PR for the delta so that we can assess what has changed.

**Comment by sandra-d** [comment]
So we're forking `node-jwks-rsa`? Could you explain why and whether there were any other alternative possibilities? (I understand if there's not but just want to make sure we understand the reason and we've documented it). I think we might need to raise, maybe in the common components channel, that we think we need to start forking this library and why.

**Comment by jjhoughton** [comment]
> It would be useful to have an initial commit with thew forked code and then a PR for the delta so that we can assess what has changed.

https://github.com/ripjar/node-jwks-rsa/pull/1/commits/cbf86536fe8c4e1fb637ca2ad56e88bd60b3cb84 this is the delta.

this https://github.com/ripjar/node-jwks-rsa/pull/1/commits/d2631bdb199b518684b10e0547733c059f3f8bb9 is me just commiting the compiled code because otherwise i couldn't get it to work

**Comment by jjhoughton** [comment]
> So we're forking `node-jwks-rsa`? Could you explain why and whether there were any other alternative possibilities? (I understand if there's not but just want to make sure we understand the reason and we've documented it). I think we might need to raise, maybe in the common components channel, that we think we need to start forking this library and why.

There are two reasons to do this
1. To make it consistent with https://github.com/ripjar/passport-openidconnect/pull/3/files
2. because otherwise it wouldn't work with node-http-connect-proxy ie the proxy jordan asked me to use for testing.

I have no Idea what the alternative might be.

**Review by SteveJM — APPROVED** [review]

**Review by SteveJM — APPROVED** [review]

**Pull request merged**
